name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: fish {0}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: fish-actions/install-fish@v1

      - name: Install Fisher
        run: curl git.io/fisher | source && fisher install jorgebucaran/fisher

      - name: Install osflavor
        run: fisher install $GITHUB_WORKSPACE
