name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: fish {0}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: fish-actions/install-fish@v1

      - name: Install Fisher
        run: curl git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish

      - name: Install fishtape
        run: fisher install jorgebucaran/fishtape

      - name: Install osflavor
        run: fisher install $GITHUB_WORKSPACE

      - name: Test osflavor
        run: fishtape $GITHUB_WORKSPACE/tests/*.fish
